version: '3'
services:
  codingassignment:
    container_name: "codingassignment"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # App port
    depends_on:
      - codingassignment-db
  codingassignment-db:
    container_name: "codingassignment-db"
    image: mariadb
    volumes:
      - ./src/main/resources/schema:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: messaging
      MYSQL_ROOT_PASSWORD: root_password
